# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 11:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booklet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='BookletEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('twocolumn', models.BooleanField()),
                ('booklet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weblatex.Booklet')),
            ],
            options={
                'ordering': ['booklet', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lyrics', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='bookletentry',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weblatex.Song'),
        ),
        migrations.AddField(
            model_name='booklet',
            name='songs',
            field=models.ManyToManyField(through='weblatex.BookletEntry', to='weblatex.Song'),
        ),
    ]
