# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 10:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weblatex', '0003_song_attribution'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedSong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.BinaryField()),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weblatex.Song')),
            ],
        ),
    ]
